sources:
  ePMC:
    query_url: 'https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PUB_TYPE%3A%22Retracted%20Publication%22&resultType=core&cursorMark={}&pageSize={}&format={}'
    article_url: https://www.ebi.ac.uk/europepmc/webservices/rest/article/{}/{}?resultType=core&format={}
products:
- retracts.json
- PMIDS_DOIS.csv
- ids.csv
- all.tsv
uri_file: 'data/uris/uris.csv'