sources:
- ePMC
products:
- retracts.json
- PMIDS_DOIS.csv
- ids.csv
- all.tsv
ePMC:
  query_url: 'https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PUB_TYPE%3A%22Retracted%20Publication%22&resultType=core&cursorMark={}&pageSize={}&format={}'
