name: Fetch data

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 9 * * MON"
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    name: Fetch data
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}   
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'      
      - name: Install Dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run retractable
        run: python main.py
      - name: Commit and Push Changes
        run: |
          git add data/*.tsv data/*.csv
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated data update" data/*
  run_nbs:
    runs-on: ubuntu-latest
    name: Run notebooks
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}   
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'      
      - name: Install Dependencies
        run: | 

          input_directory="/src/main/notebooks/"
          for notebook in "$input_directory"/*.ipynb; do
            base_filename=$(basename "${notebook%.ipynb}")
            new_filename=$(echo "$base_filename" | sed -E 's/^[0-9]+_//')
            jupyter nbconvert --to markdown "$notebook" --output "docs/${new_filename}.md"
          done
      - name: Commit and Push Changes
        run: |
          git add docs/*
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated notebook run" docs/*