name: Get data

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 9 * * MON"
  workflow_dispatch:
jobs:
  run_retractable:
    name: Retrieve retracted article data
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run retractable
      run: |
        mvn clean compile assembly:single
        java -cp target/retractable-1.0-jar-with-dependencies.jar io.github.jmillanacosta.retractable.Retractable
    - name: Commit data files
      run: |
        git add data/* 
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Actions - data updated" data/*
        git push -f
  run_notebook:
    name: Run notebooks and commit changes
    needs: run_retractable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}   
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'      
      - name: Install Dependencies
        run: | 
          pip install -r requirements.txt
          pip install jupyter
      - name: Run notebook and update Markdown
        run: |
          jupyter nbconvert --to markdown notebooks/00_basic_stats.ipynb
      - name: Commit and Push Changes
        run: |
          mv notebooks/00_basic_stats.md docs/00_basic_stats.md
          git add notebooks/* docs/* 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Actions - notebooks updated" notebooks/* docs/*
          git push -f
