name: run_retractable

on:
  pull_request:
    branches: ${GITHUB_REF##*/}
  schedule:
    - cron: "0 9 * * MON"
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    name: Fetch data
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}   
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'      
      - name: Install Dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run retractable
        run: python src/main/main.py --command fetch --sources epmc
      - name: Commit and Push Changes
        run: |
          git add --all
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Actions - fetch_data" --all
          git push
  RDF_data:
    needs: fetch_data
    runs-on: ubuntu-latest
    name: RDFy data
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}   
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'      
      - name: Install Dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run retractable
        run: python src/main/main.py --command RDF --sources all
      - name: Commit and Push Changes
        run: |
          git pull
          git add --all
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Actions - RDFy data" --all
          git push
